<?php
    if($block->IsEnabled() != 1){
        header("location: http://localhost/test/pub/");
        exit;
    }
?>

<h1>KK's Form</h1>
<form
        name="addData"
        method="post"
        id="addData"
        class="form"
        action="<?php echo $this->getFormAction(); ?>"
        data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
        data-mage-init='{"validation":{}}'>


    <div class="field field-name-name required" style="padding: 13px 0;">
        <label class="label" for="name">
            <span>Name *</span>
        </label>
        <div class="control">
            <input
                type="text"
                id="name"
                name="name"
                value=""
                title="Name"
                class="input-text required-entry"
                data-validate="{required:true}"
                autocomplete="off"
                aria-required="true"
            />
        </div>
    </div>


    <div class="field field-name-gander required" style="padding: 13px 0;">
        <label for="gender">Gender *</label><br />
        <input
            class="form-check-input"
            type="radio"
            name="gender"
            id="exampleRadios1"
            value="Male"
            required
        />
        <label class="form-check-label" for="exampleRadios1"> Male </label>
        <input
            class="form-check-input"
            type="radio"
            name="gender"
            id="exampleRadios1"
            value="Female"
            required
        />
        <label class="form-check-label" for="exampleRadios2"> Female </label>
    </div>



    <div class="field required" style="padding: 13px 0;">
        <label for="email_address" class="label">
          <span>Email *</span>
        </label>
        <div class="control">
            <input
                type="email"
                name="email"
                autocomplete="email"
                id="email_address"
                value=""
                title="Email"
                class="input-text"
                data-validate="{required:true, 'validate-email':true}"
                aria-required="true"
            />
        </div>
    </div>

    <div class="form-group" style="padding: 13px 0;">
          <label for="inputStatus" placeholder="Choose Your Status">status *</label>
        <select name="status" id="status" class="form-control" required>
            <option value="">Choose Customer or Guest</option>
            <option value="Log-in-Customer">Customer Who already logged</option>
            <option value="Guest">Guest</option>
        </select>
    </div>

    <div class="form-group" style="padding: 13px 0;">
        <label for="exampleFormControlTextarea1">Give Us Your Valuable Feedback</label>
            <textarea
                class="form-control"
                name="feedback"
                id="exampleFormControlTextarea1"
                rows="3">
            </textarea>
        </div>

    <div class="actions-toolbar" style="padding: 16px 0;">
        <div class="primary">
            <button type="submit" class="action submit primary" title="Feedback">
                <span><?= $block->escapeHtmlAttr(__('Feedback')) ?></span>
            </button>
        </div>
    </div>
</form>
